// svelte/src/components/ExchangeRateInfo.svelte
<script>
  import { currentExchangeRate, sourceCurrency, targetCurrency, loading } from '../stores.js'
</script>

{#if $currentExchangeRate !== null && !$loading}
  <div class="rate-info">
    <div class="rate-line">
      <span class="rate-label">Tasa actual</span>
      <span class="rate-value">
        1 {$sourceCurrency}
        <span class="equals">=</span>
        {$currentExchangeRate.toFixed(4)} {$targetCurrency}
      </span>
    </div>
    <div class="rate-inverse">
      1 {$targetCurrency} = {(1 / $currentExchangeRate).toFixed(4)} {$sourceCurrency}
    </div>
  </div>
{:else if $loading}
  <div class="rate-info skeleton">
    <div class="skeleton-line"></div>
    <div class="skeleton-line short"></div>
  </div>
{/if}

// Vue/src/components/ExchangeRateInfo.vue
<script>
import { useCurrencyStore } from '../stores/currencyStore'

export default {
  name: 'ExchangeRateInfo',
  setup() {
    const store = useCurrencyStore()
    return { store }
  }
}
</script>

<template>
  <div class="rate-info" v-if="store.exchangeRate !== null && !store.loading">
    <div class="rate-line">
      <span class="rate-label">Tasa actual</span>
      <span class="rate-value">
        1 {{ store.sourceCurrency }}
        <span class="equals">=</span>
        {{ store.exchangeRate?.toFixed(4) }}
        {{ store.targetCurrency }}
      </span>
    </div>
    <div class="rate-inverse">
      1 {{ store.targetCurrency }} = {{ (1 / store.exchangeRate)?.toFixed(4) }} {{ store.sourceCurrency }}
    </div>
  </div>
  <div class="rate-info skeleton" v-else-if="store.loading">
    <div class="skeleton-line"></div>
    <div class="skeleton-line short"></div>
  </div>
</template>

<style src="../../../shared/styles/exchange-rate.css"></style>
